services:
    _defaults:
        public: false

    super_brave_gdpr.annotation.reader:
        class: SuperBrave\GdprBundle\Annotation\AnnotationReader

    super_brave_gdpr.anonymizer_collection:
        class: SuperBrave\GdprBundle\Anonymizer\AnonymizerCollection
        public: true

    super_brave_gdpr.fixed_value_anonymizer:
        class: SuperBrave\GdprBundle\Anonymizer\FixedValueAnonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: fixedValue }
