services:
    _defaults:
        public: false

    superbrave_gdpr.exporter.serializer.normalizer.iterable_normalizer:
        class: Superbrave\GdprBundle\Serializer\Normalizer\IterableNormalizer
        tags:
            - { name: 'superbrave_gdpr.serializer.normalizer' }

    superbrave_gdpr.exporter.serializer.normalizer.datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags:
            - { name: 'superbrave_gdpr.serializer.normalizer' }

    Superbrave\GdprBundle\Serializer\Normalizer\AnnotationNormalizer:
        arguments:
            - '@Superbrave\GdprBundle\Annotation\AnnotationReader'
            - 'Superbrave\GdprBundle\Annotation\Export'
            - '@Superbrave\GdprBundle\Manipulator\PropertyManipulator'
        tags:
            - { name: 'superbrave_gdpr.serializer.normalizer' }

    superbrave_gdpr.exporter.serializer.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder
        tags:
            - { name: 'superbrave_gdpr.serializer.encoder' }

    superbrave_gdpr.exporter.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name: 'superbrave_gdpr.serializer.encoder' }
