services:
    _defaults:
        public: false

    Superbrave\GdprBundle\Annotation\Anonymize:
    Superbrave\GdprBundle\Annotation\Export:
    Superbrave\GdprBundle\Annotation\AnnotationReader:

    Superbrave\GdprBundle\Export\Exporter:
        arguments:
            - '@superbrave_gdpr.exporter.serializer'
        public: true

    Superbrave\GdprBundle\Anonymize\Anonymizer:
        arguments:
            - '@Superbrave\GdprBundle\Annotation\AnnotationReader'
            - '@Superbrave\GdprBundle\Anonymize\PropertyAnonymizer'
        public: true

    superbrave_gdpr.exporter.serializer:
        class: Symfony\Component\Serializer\Serializer
        factory: ['Superbrave\GdprBundle\DependencyInjection\ObjectFactory', 'createSerializer']
        arguments:
            - !tagged 'superbrave_gdpr.serializer.normalizer'
            - !tagged 'superbrave_gdpr.serializer.encoder'

    superbrave_gdpr.property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor

    Superbrave\GdprBundle\Manipulator\PropertyManipulator:
        arguments:
            - '@superbrave_gdpr.property_accessor'

    Superbrave\GdprBundle\Anonymize\AnonymizerCollection:
        public: true

    Superbrave\GdprBundle\Anonymize\PropertyAnonymizer:
        arguments:
            - '@superbrave_gdpr.property_manipulator'
            - '@superbrave_gdpr.anonymizer_collection'
