services:
    _defaults:
        public: false

    superbrave_gdpr.annotation.reader:
        class: Superbrave\GdprBundle\Annotation\AnnotationReader

    superbrave_gdpr.exporter:
        class: Superbrave\GdprBundle\Export\Exporter
        arguments:
            - "@superbrave_gdpr.exporter.serializer"
            - "xml"
        public: true

    superbrave_gdpr.anonymizer:
        class: Superbrave\GdprBundle\Anonymize\Anonymizer
        arguments:
            - "@superbrave_gdpr.annotation.reader"
            - "@superbrave_gdpr.property_anonymizer"
        public: true

    superbrave_gdpr.exporter.serializer:
        class: Symfony\Component\Serializer\Serializer
        factory: ["Superbrave\\GdprBundle\\DependencyInjection\\ObjectFactory", "createSerializer"]
        arguments:
            - !tagged "superbrave_gdpr.serializer.normalizer"
            - !tagged "superbrave_gdpr.serializer.encoder"

    superbrave_gdpr.exporter.serializer.normalizer.export_annotation:
        class: Superbrave\GdprBundle\Serializer\Normalizer\AnnotationNormalizer
        arguments:
            - "@superbrave_gdpr.annotation.reader"
            - "Superbrave\\GdprBundle\\Annotation\\Export"
            - "@superbrave_gdpr.property_manipulator"
        tags:
            - { name: "superbrave_gdpr.serializer.normalizer" }

    superbrave_gdpr.exporter.serializer.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder
        tags:
            - { name: "superbrave_gdpr.serializer.encoder" }

    superbrave_gdpr.exporter.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name: "superbrave_gdpr.serializer.encoder" }

    superbrave_gdpr.property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor

    superbrave_gdpr.property_manipulator:
        class: Superbrave\GdprBundle\Manipulator\PropertyManipulator
        arguments:
            - "@superbrave_gdpr.property_accessor"

    superbrave_gdpr.anonymizer_collection:
        class: Superbrave\GdprBundle\Anonymize\AnonymizerCollection
        public: true

    superbrave_gdpr.property_anonymizer:
        class: Superbrave\GdprBundle\Anonymize\PropertyAnonymizer
        arguments:
            - "@superbrave_gdpr.property_manipulator"
            - "@superbrave_gdpr.anonymizer_collection"
