services:
    super_brave_gdpr.base_type_anonymizer:
        abstract: true
        public: false
        arguments:
            - "@super_brave_gdpr.property_manipulator"

    super_brave_gdpr.fixed_value_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\FixedValueAnonymizer
        parent: super_brave_gdpr.base_type_anonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: fixed }

    super_brave_gdpr.date_time_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\DateTimeAnonymizer
        parent: super_brave_gdpr.base_type_anonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: dateTime }

    super_brave_gdpr.ip_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\IpAnonymizer
        parent: super_brave_gdpr.base_type_anonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: ip }

    super_brave_gdpr.object_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\ObjectAnonymizer
        public: false
        arguments:
            - "@super_brave_gdpr.anonymizer"
        tags:
            - { name: super_brave_gdpr.anonymizer, type: object }

    super_brave_gdpr.collection_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\ArrayAnonymizer
        public: false
        arguments:
            - "@super_brave_gdpr.object_anonymizer"
        tags:
            - { name: super_brave_gdpr.anonymizer, type: collection }
