services:
    _defaults:
        public: false

    super_brave_gdpr.annotation.reader:
        class: SuperBrave\GdprBundle\Annotation\AnnotationReader

    super_brave_gdpr.exporter:
        class: SuperBrave\GdprBundle\Export\Exporter
        arguments:
            - "@super_brave_gdpr.exporter.serializer"
            - "xml"
        public: true

    super_brave_gdpr.anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Anonymizer
        arguments:
            - "@super_brave_gdpr.annotation.reader"
        public: true

    super_brave_gdpr.exporter.serializer:
        class: Symfony\Component\Serializer\Serializer
        factory: ["SuperBrave\\GdprBundle\\DependencyInjection\\ObjectFactory", "createSerializer"]
        arguments:
            - !tagged "super_brave_gdpr.serializer.normalizer"
            - !tagged "super_brave_gdpr.serializer.encoder"

    super_brave_gdpr.exporter.serializer.normalizer.export_annotation:
        class: SuperBrave\GdprBundle\Serializer\Normalizer\AnnotationNormalizer
        arguments:
            - "@super_brave_gdpr.annotation.reader"
            - "SuperBrave\\GdprBundle\\Annotation\\Export"
            - "@super_brave_gdpr.property_manipulator"
        tags:
            - { name: "super_brave_gdpr.serializer.normalizer" }

    super_brave_gdpr.exporter.serializer.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder
        tags:
            - { name: "super_brave_gdpr.serializer.encoder" }

    super_brave_gdpr.exporter.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name: "super_brave_gdpr.serializer.encoder" }

    super_brave_gdpr.property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor

    super_brave_gdpr.property_manipulator:
        class: SuperBrave\GdprBundle\Manipulator\PropertyManipulator
        arguments:
            - "@super_brave_gdpr.property_accessor"

    super_brave_gdpr.anonymizer_collection:
        class: SuperBrave\GdprBundle\Anonymize\AnonymizerCollection
        public: true

    super_brave_gdpr.property_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\PropertyAnonymizer
        arguments:
            - "@super_brave_gdpr.property_manipulator"
            - "@uper_brave_gdpr.anonymizer_collection"

    super_brave_gdpr.fixed_value_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\FixedValueAnonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: fixedValue }

    super_brave_gdpr.date_time_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\DateTimeAnonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: dateTime }

    super_brave_gdpr.ip_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\IpAnonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: ip }
