build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
  coverage:
    tests:
      override:
        - command: bin/phpunit --log-junit build/logs/phpunit.xml --coverage-clover build/logs/clover.xml
          coverage:
            file: build/logs/clover.xml
            format: clover
checks:
  php: true
coding_style:
  php:
    spaces:
      other:
        after_type_cast: false
filter: {  }
