language: php

sudo: false

matrix:
  include:
    - php: 7.2

before_install: composer self-update

install: composer install

before_script:
  - mkdir -p build/logs

script:
  - bin/phpunit --log-junit build/logs/phpunit.xml
  - bin/phpcs --report-full --report-junit=build/logs/phpcs.xml
